### ISSUE TITLE
->toArray() not required

### ISSUE THREAD

**Issue by anikgoel** [skopes2/Lite#57]
https://github.com/skopes2/Lite/blob/d69786a193be1fcacdcbd6c0cc9a33c757e9839a/app/Http/Controllers/Frontend/FrontendController.php#L65

->toArray() function is not required to be use. It is unnecessary call to convert the object to array as you can directly use the data which is coming from eloquent. 

What issue it can cause - 
1. Suppose, if there is null returning from "->first()", it will throw and error which is not handled. So instead you can just terminate your line at "->first()" and in the next line you can just check "if(isset($project_name->name))"

2. When you call to "->toArray()", it ultimately calls 1 function which is not required and can affect performance time in future when the codebase would be large.

**Comment by ervivekmahajan** [comment]
Hello Anik,

So I have removed this line of code. As you are right this is extra one. As Package name is already coming from another query. I have updated in my branch and staging branch both.

Vivek

**Comment by anikgoel** [comment]
ok, cool. looks great now. Also, make sure you are not using "->toArray()" function in the code. With my experience in laravel, it is never required and it just create problem in lot of cases
