### ISSUE TITLE
Duplicate database query

### ISSUE THREAD

**Issue by anikgoel** [skopes2/Lite#59]
https://github.com/skopes2/Lite/blob/d69786a193be1fcacdcbd6c0cc9a33c757e9839a/app/Http/Controllers/Frontend/FrontendController.php#L90

Just above this line, same call is being made to database. Please change code so that there are not multiple queries going to database to fetch exactly same data. It will really affect performance.

**Comment by ervivekmahajan** [comment]
Hello Anik,

This has been removed as it was added to get the Package name in ELSE condition of Old projects in Navigation function.

Vivek
